"""
constants.py

Centralized, immutable constants used across the FinSight AI platform.
Keeping these in one module avoids "magic values" scattered through the
codebase and gives every later phase (auth, dashboard, ML, etc.) a single
source of truth to import from.
"""

from enum import Enum


# ==========================================================
# Application Metadata
# ==========================================================
APP_TITLE: str = "FinSight AI"
APP_TAGLINE: str = "AI-Powered Stock Market Intelligence & Portfolio Analytics Platform"
APP_VERSION: str = "0.1.0"
APP_ICON: str = "📈"

# ==========================================================
# Date / Time Formats
# ==========================================================
DATE_FORMAT: str = "%Y-%m-%d"
DATETIME_FORMAT: str = "%Y-%m-%d %H:%M:%S"
DISPLAY_DATE_FORMAT: str = "%d %b %Y"
TIMEZONE: str = "Asia/Kolkata"

# ==========================================================
# Pagination / Limits
# ==========================================================
DEFAULT_PAGE_SIZE: int = 25
MAX_PAGE_SIZE: int = 200
MAX_WATCHLIST_ITEMS: int = 50
MAX_LOGIN_ATTEMPTS: int = 5

# ==========================================================
# Market / Stock Related
# ==========================================================
DEFAULT_CURRENCY: str = "INR"
DEFAULT_EXCHANGE_SUFFIX: str = ".NS"   # NSE suffix used by yfinance
SUPPORTED_EXCHANGES: tuple = ("NSE", "BSE", "NASDAQ", "NYSE")

# ==========================================================
# File / Path Related
# ==========================================================
LOG_DIR_NAME: str = "logs"
REPORTS_DIR_NAME: str = "reports/generated"
ASSETS_DIR_NAME: str = "assets"


class UserRole(str, Enum):
    """Roles table enumeration - mirrored in the database `roles` table."""
    ADMIN = "admin"
    ANALYST = "analyst"
    USER = "user"


class TransactionType(str, Enum):
    """Buy/Sell enumeration used by the `transactions` table."""
    BUY = "BUY"
    SELL = "SELL"


class AlertCondition(str, Enum):
    """Condition types supported by the `alerts` table."""
    PRICE_ABOVE = "PRICE_ABOVE"
    PRICE_BELOW = "PRICE_BELOW"
    PERCENT_CHANGE = "PERCENT_CHANGE"


class ReportType(str, Enum):
    """Report categories generated by the `reports` module (Phase 2+)."""
    PORTFOLIO_SUMMARY = "PORTFOLIO_SUMMARY"
    PREDICTION_SUMMARY = "PREDICTION_SUMMARY"
    TRANSACTION_HISTORY = "TRANSACTION_HISTORY"


# ==========================================================
# HTTP / API Status Messages
# ==========================================================
MSG_SUCCESS: str = "Operation completed successfully."
MSG_FAILURE: str = "Operation failed. Please try again."
MSG_DB_CONNECTION_ERROR: str = "Unable to connect to the database."
MSG_INVALID_INPUT: str = "Invalid input provided."
